
# ██╗██████╗░██╗██████╗░██╗██╗░░░██╗███╗░░░███╗
# ██║██╔══██╗██║██╔══██╗██║██║░░░██║████╗░████║
# ██║██████╔╝██║██║░░██║██║██║░░░██║██╔████╔██║
# ██║██╔══██╗██║██║░░██║██║██║░░░██║██║╚██╔╝██║
# ██║██║░░██║██║██████╔╝██║╚██████╔╝██║░╚═╝░██║
# ╚═╝╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░╚═════╝░╚═╝░░░░░╚═╝

settings:

  towny-status-screen:

    town-screen-has-name: "&fГлава: #E6DF9E{name} {surname} {{age}}"
    town-screen-no-name: "&fГлава: #E6DF9EНе выбрал RP имя"

    nation-screen-has-name: "&fГлава: #E6DF9E{name} {surname} {{age}}"
    nation-screen-no-name: "&fГлава: #E6DF9EНе выбрал RP имя"

  placeholder:

    no-name: "Не выбрал RP имя"